version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo npm install @neuralegion/nexploit-cli -g --unsafe-perm=true || true
      - run:
          name: Starting Nexploit scan ðŸ
          command: >
              echo 'export SCAN_ID=$(nexploit-cli scan:run --token $NEXPLOIT_TOKEN
              --name "BC Scan from CircleCI"
              --crawler https://brokencrystals.neuralegion.com
              --smart)' >> $BASH_ENV
      - run: 
          name: Get the output scan url ðŸ”—
          command: |
            printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID"
