version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - run: sudo npm install @neuralegion/nexploit-cli -g --unsafe-perm=true || true
      - run:
          name: Starting Nexploit scan ðŸ
          command: >
              SCAN_ID=$(nexploit-cli scan:run --token $NEXPLOIT_TOKEN
              --name "Test CircleCI scan"
              --crawler https://juice-shop.herokuapp.com/
              --smart)
              bash -c 'echo $SCAN_ID'
              export SCAN_ID
              bash echo $SCAN_ID
              echo $SCAN_ID
              printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID"
      - run: 
          name: Get the output scan url ðŸ”—
          command: |
            export SCAN_ID
            echo $SCAN_ID
            printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID"
